Add/command to spin shooter motor at 4000 rpm at start up
frc2357/FRC-2020 pull request #102
Opened 2020-02-23 19:44 UTC by CrazyFloob

The shooter subsystem runs at 4000rpm on startup, and the shoot command runs at 6000rpm on initialize, and runs down to 4000rpm on end.

2020-02-23 19:51 UTC, Stick-2357 requested changes

2020-02-23 19:51 UTC, Stick-2357 commented on robotbase/src/main/java/com/systemmeltdown/robot/commands/ShootCommand.java
> +        super.initialize();
Unnecessary super call.

2020-02-23 19:53 UTC, CrazyFloob commented on robotbase/src/main/java/com/systemmeltdown/robot/commands/ShootCommand.java
> +        super.initialize();
Fixed.

2020-02-27 00:10 UTC, mhensz approved these changes

2020-03-01 03:03 UTC, coderkevin commented
Definitely not necessary or desired.

2020-03-01 03:03 UTC, closed without merging