Added Intake Sub
frc2357/FRC-2020 pull request #5
Opened 2020-01-10 01:08 UTC by Jbrn-2357

Added Intake subsystem.  Some values within the changeArmPosition method could be incorrect, needs to be tested to find the correct values.

2020-01-11 17:43 UTC, NolanCampbell2357 requested changes

2020-01-11 17:43 UTC, CrazyFloob commented on robotbase/src/main/java/com/systemmeltdown/robot/subsystems/IntakeSub.java
> +
Excess white space.

2020-01-11 17:43 UTC, CrazyFloob commented on robotbase/src/main/java/com/systemmeltdown/robot/subsystems/IntakeSub.java
> +
Excess white space.

2020-01-11 17:43 UTC, CrazyFloob commented on robotbase/src/main/java/com/systemmeltdown/robot/subsystems/IntakeSub.java
> +
Excess white space.

2020-01-11 17:43 UTC, CrazyFloob commented on robotbase/src/main/java/com/systemmeltdown/robot/subsystems/IntakeSub.java
> +
Excess white space.

2020-01-11 17:43 UTC, CrazyFloob commented on robotbase/src/main/java/com/systemmeltdown/robot/subsystems/IntakeSub.java
> +
Excess white space.

2020-01-12 19:52 UTC, GameMagma requested changes
Delete the excess lines (line 10, line 16, line 19, line 29, and line 38) and then it's fine.

2020-01-12 23:44 UTC, merged